name: Deploy Frontend React (comissoesweb)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do Código
        uses: actions/checkout@v3

      - name: 2. Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 3. Construir e Enviar Imagem Docker (Frontend Nginx)
        # Usa o Dockerfile multi-stage criado
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Usa o secret NOVO: WEB_PROJECT_REPO_NAME (Ex: comissoesweb)
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.WEB_PROJECT_REPO_NAME }}:latest

      - name: 4. Conectar no Servidor, Configurar Nginx e Fazer Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # --- Cria o diretório de trabalho ---
            echo "Criando diretório de trabalho..."
            mkdir -p /home/deployer/${{ secrets.WEB_PROJECT_REPO_NAME }}
            cd /home/deployer/${{ secrets.WEB_PROJECT_REPO_NAME }}
            
            # --- Cria o docker-compose.yml (com WEB_HOST_PORT) ---
            echo "Criando docker-compose.yml..."
            cat << EOF > docker-compose.yml
            services:
              frontend:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.WEB_PROJECT_REPO_NAME }}:latest
                container_name: ${{ secrets.WEB_PROJECT_REPO_NAME }}_frontend
                restart: unless-stopped
                ports:
                  # Expondo na porta 8084 do host para Nginx
                  - "127.0.0.1:8084:80" 
                networks:
                  - frontend-net
            
            networks:
              frontend-net:
            EOF

            # --- Cria a configuração do Nginx ---
            echo "Criando configuração do Nginx..."
            cat << EOF > nginx.conf
            server { 
                listen 80;
                server_name ${{ secrets.WEB_PROJECT_DOMAIN }}; 
                return 301 https://\$host\$request_uri; 
            }
            
            server {
                listen 443 ssl http2;
                server_name ${{ secrets.WEB_PROJECT_DOMAIN }}; 

                ssl_certificate /etc/letsencrypt/live/promptweb.com.br/fullchain.pem; 
                ssl_certificate_key /etc/letsencrypt/live/promptweb.com.br/privkey.pem; 
                include /etc/letsencrypt/options-ssl-nginx.conf; 
                ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 

                location / { 
                    proxy_pass http://127.0.0.1:8084; 
                    proxy_set_header Host \$host; 
                    proxy_set_header X-Real-IP \$remote_addr; 
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for; 
                    proxy_set_header X-Forwarded-Proto https; 
                }
            }
            EOF

            # --- Bloco de Administração do Servidor (Nginx) ---
            NGINX_CONF_FILE="/etc/nginx/sites-available/${{ secrets.WEB_PROJECT_DOMAIN }}" 
            NGINX_LINK_FILE="/etc/nginx/sites-enabled/${{ secrets.WEB_PROJECT_DOMAIN }}"

            echo "Instalando e Configurando Nginx para ${{ secrets.WEB_PROJECT_REPO_NAME }}..."
            sudo /usr/bin/mv /home/deployer/${{ secrets.WEB_PROJECT_REPO_NAME }}/nginx.conf $NGINX_CONF_FILE
            sudo /usr/bin/ln -sf $NGINX_CONF_FILE $NGINX_LINK_FILE
            
            if ! sudo /usr/sbin/nginx -t; then 
              echo "==================================================="
              echo "ERRO CRÍTICO NA CONFIGURAÇÃO NGINX. REMOVENDO ARQUIVO."
              echo "==================================================="
              echo "Conteúdo do arquivo."
              echo "#====#====#====#====#====#====#====#"
              sudo cat "$NGINX_CONF_FILE"
              echo "#====#====#====#====#====#====#====#"
              # REMOÇÃO DO ARQUIVO COM ERRO E LINK (Melhoria de Erro)
              sudo rm -f "$NGINX_LINK_FILE" 
              sudo rm -f "$NGINX_CONF_FILE" 
              exit 1; 
            fi

            # --- Executa o Deploy Docker ---
            echo "Parando contêineres antigos..."
            docker compose down --remove-orphans 

            echo "Removendo contêineres nomeados..."
            # Usa aspas duplas no nome do contêiner
            docker rm -f "${{ secrets.WEB_PROJECT_REPO_NAME }}_frontend" || true 

            echo "Baixando nova imagem..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.WEB_PROJECT_REPO_NAME }}:latest

            echo "Iniciando Frontend..."
            docker compose up -d

            echo "Recarregando Nginx..."
            sudo /usr/bin/systemctl reload nginx

            echo "✅ Deploy Frontend concluído com sucesso!"
            echo "   Acessível em: https://${{ secrets.WEB_PROJECT_DOMAIN }}"